### ISSUE TITLE
i can not read memory from eToken 5110

### ISSUE THREAD

**Issue by SantiagoAndresHurtado** [LudovicRousseau/PyKCS11#75] opened 2020-09-23 20:52 UTC
#### Your system information
* Operating system used: Ubuntu 20.04.1 LTS
* PyKCS11 version: 1.5.9
* Python version: 3.8
* PKCS#11 library used: SafeNet eToken 5110 ("libeTPkcs11.so") 
[library.zip](https://github.com/LudovicRousseau/PyKCS11/files/5271817/library.zip)

#### Please describe your issue in as much detail as possible:
I want to verify my signature and I want to extract the certificate with the 'getAttributeValue' function

Describe what _did_ happen.
Using 'signature' script in the samples folder when it try to verify the signature the result is false, but the sign is correct. 
Using 'dumpit' script in the samples folder when it try to read the objects this error appears: Segmentation fault (core dumped)

**Comment by LudovicRousseau** [comment] 2020-09-24 07:04
I think your bug is a duplicate of https://github.com/LudovicRousseau/PyKCS11/issues/56

I provided a dumpit test patch in https://github.com/LudovicRousseau/PyKCS11/issues/56#issuecomment-489560929

**Comment by SantiagoAndresHurtado** [comment] 2020-09-24 14:35
That patch solve the problem to read the certificate! 
But it still can not verify the signature. But it is not a problem if i add the signature and certificate to the original file. 

Thanks for your help!

**Comment by LudovicRousseau** [comment] 2020-09-24 16:05
The `signature.py` code is a sample code so very simple and stupid.
For example it uses the first public key it finds to verify the signature. That may not be the correct key.

**Closed by LudovicRousseau** 2020-09-24 16:05 UTC
