### ISSUE TITLE
Slot list empty using Luna SA PKCS#11 lib

### ISSUE THREAD

**Issue by xzr** [LudovicRousseau/PyKCS11#10] opened 2017-05-09 12:59 UTC
Hi, I'm running into a problem where I'm not able to retrieve the slot list through PyKCS11 when using the PKCS#11 library provided by Safenet Luna SA HSM. 

Using pkcs11-tool from the OpenSC project and loading up the lib, the call works fine and all slots get listed. 

When I do the same with PyKCS11 I get an empty list in return.

I used pkcs11-spy library to debug the issue and I've attached the log comparison

```
PyKCS#11

*************** OpenSC PKCS#11 spy *****************
Loaded: "/usr/safenet/lunaclient/lib/libCryptoki2_64.so"

0: C_GetFunctionList
2017-05-09 15:47:33.415
Returned:  0 CKR_OK

1: C_GetInfo
2017-05-09 15:47:33.415
[out] pInfo: 
      cryptokiVersion:         2.20
      manufacturerID:         ' SafeNet, Inc.                  '
      flags:                   0
      libraryDescription:     ' Chrystoki                      '
      libraryVersion:          5.1
Returned:  0 CKR_OK

2: C_GetSlotList
2017-05-09 15:49:28.662
[in] tokenPresent = 0x0
[out] pSlotList: 
[out] *pulCount = 0x0
Returned:  0 CKR_OK





pkcs11-tool

*************** OpenSC PKCS#11 spy *****************
Loaded: "/usr/safenet/lunaclient/lib/libCryptoki2_64.so"

0: C_GetFunctionList
2017-05-09 15:40:37.891
Returned:  0 CKR_OK

1: C_Initialize
2017-05-09 15:40:37.891
[in] pInitArgs = (nil)
Returned:  0 CKR_OK

2: C_GetSlotList
2017-05-09 15:40:38.959
[in] tokenPresent = 0x0
[out] pSlotList: 
Count is 4
[out] *pulCount = 0x4
Returned:  0 CKR_OK

3: C_GetSlotList
2017-05-09 15:40:38.959
[in] tokenPresent = 0x0
[out] pSlotList: 
Slot 0
Slot 1
Slot 2
Slot 3
[out] *pulCount = 0x4
Returned:  0 CKR_OK
```
It would seem that the library in question requires C_Initialize to be called, before the library can be queried. Is there a way I can instruct PyKCS11 to make that call (didn't find it in the api at least)?

**Comment by xzr** [comment] 2017-05-09 13:15
Okay it seems to be quite a simple fix. 

I added the following code in __init.py__:


```
def initialize(self):
    rv = self.lib.C_Initialize()
    if rv != CKR_OK:
        raise PyKCS11Error(rv)
```


Then tested it out in python:

```
(env) xzr@xzr:~/hsm/tool$ PKCS11SPY=/usr/safenet/lunaclient/lib/libCryptoki2_64.so PKCS11SPY_OUTPUT=spylog_init.txt python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import PyKCS11
>>> lib = PyKCS11.PyKCS11Lib()
>>> lib.load('/usr/lib/x86_64-linux-gnu/pkcs11-spy.so')
>>> lib.initialize()
>>> lib.getSlotList()
[0, 1, 2, 3]
```

Would you like me to make a patch out of it? Apparently some libraries require C_Initialize to be called.

**Comment by LudovicRousseau** [comment] 2017-05-09 13:53
The problem is with ``libCryptoki2_64.so`` (not PyKCS11 😃).

PyKCS11 calls ``C_GetInfo()`` to know if the library is initialized or not. PyKCS11 is expecting ``CKR_CRYPTOKI_NOT_INITIALIZED`` and would then call ``C_Initialize()`` but ``libCryptoki2_64.so`` returns ``CKR_OK`` instead.
https://github.com/LudovicRousseau/PyKCS11/blob/master/src/pkcs11lib.cpp#L79

Then ``libCryptoki2_64.so`` continues to return ``CKR_OK`` to ``C_GetSlotList()`` even if the library is still _not_ initialized.

One way to fix the problem would be to always call ``C_Initialize()`` in ``Load()`` (and remove the use of ``m_bAutoInitialized``)
https://github.com/LudovicRousseau/PyKCS11/blob/master/src/pkcs11lib.cpp#L54

**Comment by xzr** [comment] 2017-05-09 13:56
Hmm or maybe it would be possible to add a flag to the load function to force initialize regardless of what the library returns?

And I'm aware it's not a fault in PyKCS11, a lot of these vendor libraries have minds of their own :)

**Comment by LudovicRousseau** [comment] 2017-05-09 14:05
I proposed this patch:
```patch
--- /var/folders/5h/3d1x67_x5g30t36wypgxpmpc0000gn/T//vuXZV8___init__.py    2017-05-09 16:03:33.000000000 +0200
+++ PyKCS11/__init__.py 2017-05-09 16:00:17.000000000 +0200
@@ -454,7 +454,7 @@ class PyKCS11Lib(object):
             pkcs11dll_filename = os.getenv("PYKCS11LIB")
             if pkcs11dll_filename is None:
                 raise PyKCS11Error(-1, "No PKCS11 library specified (set PYKCS11LIB env variable)")
-        rv = self.lib.Load(pkcs11dll_filename, True)
+        rv = self.lib.Load(pkcs11dll_filename)
         if rv == 0:
             raise PyKCS11Error(-1, pkcs11dll_filename)
 
--- /var/folders/5h/3d1x67_x5g30t36wypgxpmpc0000gn/T//jglGca_pkcs11lib.cpp  2017-05-09 16:03:33.000000000 +0200
+++ src/pkcs11lib.cpp   2017-05-09 15:59:27.000000000 +0200
@@ -51,7 +51,7 @@ CPKCS11Lib::~CPKCS11Lib(void)
    Unload();
 }
 
-bool CPKCS11Lib::Load(const char* szLib, bool bAutoCallInitialize)
+bool CPKCS11Lib::Load(const char* szLib)
 {
    CK_RV rv;
    Unload();
@@ -73,16 +73,10 @@ bool CPKCS11Lib::Load(const char* szLib,
        return false;
    }
 
-   if (bAutoCallInitialize)
-   {
-       CK_INFO infos;
-       if (m_pFunc->C_GetInfo(&infos) == CKR_CRYPTOKI_NOT_INITIALIZED)
-       {
-           m_bAutoInitialized = m_bFinalizeOnClose = CKR_OK == m_pFunc->C_Initialize(NULL);
-       }
-       else
-           m_bAutoInitialized = true;
-   }
+   rv = m_pFunc->C_Initialize(NULL);
+   if (CKR_OK != rv)
+       return false;
+
    return true;
 }
 
--- /var/folders/5h/3d1x67_x5g30t36wypgxpmpc0000gn/T//dbaFWa_pkcs11lib.h    2017-05-09 16:03:33.000000000 +0200
+++ src/pkcs11lib.h 2017-05-09 16:00:12.000000000 +0200
@@ -50,7 +50,7 @@ class CPKCS11Lib
 public:
    CPKCS11Lib(void);
    ~CPKCS11Lib(void);
-   bool Load(const char* szLib, bool bAutoCallInitialize);
+   bool Load(const char* szLib);
    bool Unload();
 
    CK_RV C_Initialize();
```

**Comment by xzr** [comment] 2017-05-09 14:07
As long as there's no harm in always calling it, it should probably be good.

Cheers for the fast turn-around! :)

**Comment by LudovicRousseau** [comment] 2017-05-09 14:40
Fixed in https://github.com/LudovicRousseau/PyKCS11/commit/43b9317379c043e2a34f7b0ef32fa5ca24e3ae24

Thanks

**Closed by LudovicRousseau** 2017-05-09 14:40 UTC

**Comment by xzr** [comment] 2017-05-09 16:55
Fantastic, thank you very much!
