### ISSUE TITLE
AES CBC encryption issue

### ISSUE THREAD

**Issue by alxnik** [LudovicRousseau/PyKCS11#9] opened 2017-04-30 21:00 UTC
Hello,
I'm trying to work with AES CBC (and GCM) encryption using the following code. No matter what I try, I cannot pass the IV to the encrypting function, instead I always get "TypeError: unsupported CK_MECHANISM Parameter type.". I have tried passing a string object, a byte object as well as a list of single bytes. Size doesn't seem to matter.

Any ideas?

```
AESKeyTemplate =  [
        (CKA_CLASS, CKO_SECRET_KEY),
        (CKA_KEY_TYPE, CKK_AES),
        (CKA_TOKEN, CK_TRUE),
        (CKA_PRIVATE, CK_FALSE),
        (CKA_ENCRYPT, CK_TRUE),
        (CKA_DECRYPT, CK_TRUE),
        (CKA_SIGN, CK_FALSE),
        (CKA_VERIFY, CK_FALSE),
        (CKA_VALUE_LEN, 32),
        (CKA_LABEL, "TestAESKey"),
        (CKA_ID, (0x01,))
    ]

AESKey = session.generateKey(AESKeyTemplate)

session.encrypt(AESKey, Data, PyKCS11.Mechanism(CKM_AES_CBC, '1234567812345678'))
```

**Comment by LudovicRousseau** [comment] 2017-05-01 09:52
No idea. I never used AES yet.

Please provide a patch if you find the bug, or provide a sample code if you find how to use ``encrypt()``.

**Comment by alxnik** [comment] 2017-05-01 11:03
It seems to be an issue with python 3, not AES and it seems complicated.

First of all, to_param_string() returns bytes objects in case of py3 and str objects in case of py2. 
This means that PyString_Check($input) in pykcs11.i:235 will always fail in case of py3.

Again, if this issue is fixed, SWIG_AsCharPtrAndSize doesn't work as expected in case of py3.

I was able to have everything work by making to_param_string() always return str as well as making the typemap as follows (recommended way to portably handle strings in py2 & py3):

```
%typemap(in) void* {
    char *buf;
    size_t sz;
    // If the value being set is of string type:
    if (PyUnicode_Check($input)) {
    	arg2 = PyUnicode_DATA($input);
      }
    else {
      // If the value being set is of CK_RSA_PKCS_OAEP_PARAMS type:
      int res2 = SWIG_ConvertPtr($input, &arg2, $descriptor(CK_RSA_PKCS_OAEP_PARAMS*), 0 |  0 );
      if (!SWIG_IsOK(res2)) {
        SWIG_exception_fail(SWIG_ArgError(res2), "unsupported CK_MECHANISM Parameter type.");
      }
    }
}
```

However I don't have the time to test the solution and I strongly believe it needs much more testing. Also the "CK_RSA_PKCS_OAEP_PARAMS type" is a bit of a hack.

**Comment by danni** [comment] 2017-05-19 07:40
I've run into this too. Perhaps handling as a `ckbytelist` would be better?

**Comment by 31z4** [comment] 2017-05-25 07:13
Hey @LudovicRousseau any plans to fix this? https://github.com/LudovicRousseau/PyKCS11/blob/master/src/pykcs11.i#L235 doesn't work in case of Python 3 as @alxnik described. `to_param_string` always returns `bytes` in Python 3 https://github.com/LudovicRousseau/PyKCS11/blob/977eee2c30bdcc683784ff9a64eb48183bb18e59/PyKCS11/__init__.py#L25-L33

**Comment by danni** [comment] 2017-05-25 07:33
I spent a bit of time trying to massage the AES support in PyKCS11, especially so I could stream files through AES. I ultimately found the SWIG generated code too inaccessible and started writing a new binding in Cython: https://github.com/danni/python-pkcs11

**Comment by LudovicRousseau** [comment] 2017-05-28 14:19
As I wrote, a tested patch would be welcome, or a support contract.

**Comment by LudovicRousseau** [comment] 2017-05-30 09:08
I can reproduce the problem.
My sample works fine using Python2, but fails as you reported with Python3.

My test sample:
``` python
#!/usr/bin/env python

from PyKCS11 import *

pkcs11 = PyKCS11Lib()
pkcs11.load()  # define environment variable PYKCS11LIB=YourPKCS11Lib

slot = pkcs11.getSlotList()[0]

session = pkcs11.openSession(slot, CKF_SERIAL_SESSION | CKF_RW_SESSION)
session.login("1234")

AESKeyTemplate =  [
        (CKA_CLASS, CKO_SECRET_KEY),
        (CKA_KEY_TYPE, CKK_AES),
        (CKA_TOKEN, CK_TRUE),
        (CKA_PRIVATE, CK_FALSE),
        (CKA_ENCRYPT, CK_TRUE),
        (CKA_DECRYPT, CK_TRUE),
        (CKA_SIGN, CK_FALSE),
        (CKA_VERIFY, CK_FALSE),
        (CKA_VALUE_LEN, 32),
        (CKA_LABEL, "TestAESKey"),
        (CKA_ID, (0x01,))
    ]

AESKey = session.generateKey(AESKeyTemplate)

DataIn = [0] * 32
print(DataIn)

DataOut = session.encrypt(AESKey, DataIn, PyKCS11.Mechanism(CKM_AES_CBC, '1234567812345678'))
print(DataOut)

DataCheck = session.decrypt(AESKey, DataOut, PyKCS11.Mechanism(CKM_AES_CBC, '1234567812345678'))
print(DataCheck)
```

**Comment by 31z4** [comment] 2017-05-30 10:09
@LudovicRousseau good! Please consider using tox for running tests against different Python versions. I bet there could be other issues as well.

**Comment by LudovicRousseau** [comment] 2017-05-30 11:20
The problem with tox or any other automatic testing tool for PyKCS is that PyKCS uses an external PKCS#11 library (and possibly a smart card reader and smart card). It is not as easy as to check the value returned by a method with no side effect.

Since a few weeks I am using SoftHSM https://github.com/opendnssec/SoftHSMv2. Maybe it is possible to use it for automatic testing.

As always, patches are welcome.

**Comment by danni** [comment] 2017-05-30 11:48
Have had considerable success using SoftHSMv2 for integration tests,
however it has a limited set of mechanisms it supports. You can manage
quite a bit however with `skip` directives testing what PKCS#11 module is
being used.

**Comment by LudovicRousseau** [comment] 2017-05-30 12:48
OK to use tox and SoftHSMv2 for integration tests.

My first problem is: how to patch ``setup.py`` so that ``python setup.py test`` works with a minimum of efforts?

Do I have to migrate from distutils to setuptools?

**Comment by LudovicRousseau** [comment] 2017-05-30 13:44
From https://tox.readthedocs.io/en/latest/example/basic.html#integration-with-setup-py-test-command it is discouraged to mix tox with ``python setup.py test``.

**Comment by LudovicRousseau** [comment] 2017-05-30 14:27
I think that using strings to represent a binary buffer was an error.
I do plan to use a ``ckbytelist`` instead and do the conversions in ``__init__.py`` instead of using complex SWIG code.

**Comment by LudovicRousseau** [comment] 2017-06-04 09:55
The problem is not yet solved. But now I have Unitary Tests in place. Results are visible at https://travis-ci.org/LudovicRousseau/PyKCS11
- OK for Python 2.7
- KO for Python 3.6

I also tried to use tox but I have problem loading the native code library. If someone can have a look at my ``tox.ini`` file https://github.com/LudovicRousseau/PyKCS11/blob/master/tox.ini and make it work that would be appreciated.

**Comment by danni** [comment] 2017-06-04 10:45
Your problem is using a ckbytelist is not sufficient for a number of mechanisms, as there's quite a few that cannot be easily represented with `struct.pack` (looking at you ECDH1).

**Comment by LudovicRousseau** [comment] 2017-06-04 13:52
Exact. There is already a special code for ``CK_RSA_PKCS_OAEP_PARAMS`` for example.
https://github.com/LudovicRousseau/PyKCS11/blob/master/src/pykcs11.i#L266
https://github.com/LudovicRousseau/PyKCS11/blob/master/PyKCS11/__init__.py#L743

I guess we will need a ``CK_ECDH1_DERIVE_PARAMS`` equivalent.

**Comment by LudovicRousseau** [comment] 2017-06-05 13:32
The issue should be fixed in https://github.com/LudovicRousseau/PyKCS11/commit/a4dc80c3d7bde5d7a355c5fb02fe9dc8f8deea4e

I have not yet touched the ``RSAOAEPMechanism``. I guess the same problem is present since it also uses ``to_param_string()``

**Closed by LudovicRousseau** 2017-06-05 13:32 UTC
Labels: help wanted
